name: Sync fork

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  sync:
    if: false
    name: Sync fork
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync fork
        run: gh repo sync ${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}

      - uses: gautamkrishnar/keepalive-workflow@v1
